changelog:
  categories:
    - title: 🚀 Features
      labels:
        - feature
        - enhancement
    - title: 🐛 Bug Fixes
      labels:
        - bug
        - fix
    - title: 🧰 Maintenance
      labels:
        - chore
        - refactor
        - documentation
    - title: 🔧 Performance Improvements
      labels:
        - performance
        - optimization
    - title: 🧪 Testing
      labels:
        - test
    - title: 🔒 Security
      labels:
        - security
    - title: 📦 Dependencies
      labels:
        - dependencies
    - title: 🎨 UI/UX
      labels:
        - ui
        - ux
        - design
    - title: 📝 Other Changes
      labels:
        - "*"
